name: Publish to Curseforge

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Get the specified release by tag
      - uses: octokit/request-action@v2.x
        id: get_release_by_tag
        with:
          route: GET /repos/{owner}/{repo}/releases/tags/{tag}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: robinraju/release-downloader@v1.8
        id: get_release_assets
        with:
          tag: ${{ inputs.tag }}
          fileName: "*.jar"
          out-file-path: "assets"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: kETAhKGy
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 631523
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          loaders: |
            neoforge
          dependencies: |
            ex-nihilo-sequentia(required){modrinth:WhVa4xyw}{curseforge:400012}

          files: "${{ fromJson(steps.get_release_assets.outputs.downloaded_files)[0] }}"
          changelog: "${{ fromJson(steps.get_release_by_tag.outputs.data).body }}"

